//https://leetcode.com/problems/find-the-difference/
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
#include <iostream>

using namespace std;
class Solution {
    public:
        char findTheDifference(string s, string t) {
            sort(s.begin(), s.end());
            sort(t.begin(), t.end());
            int i = 0, j = 0;
            while(i < s.size()) {
                if (s[i++] != t[j++]) {
                    cout << "found: " << t[j-1];
                    return t[j-1];
                } else cout << s[i-1] << " " << t[j-1] << endl;
            }
            cout << "Came out...but found: " << t[j] << endl;
            if (i == s.size()) return t[j];
            return '0';
        }
};

int main()
{
    Solution s;
    cout << s.findTheDifference("acd", "abcd") << endl;

    return 0;
}
